<LANGUAGE="VBSCRIPT">
<html>

<body>

<h1>dérive<h2>&nbsp;<i class="ion ion-merge"></i> navigating the digital landscape</h2></h1>
<p>&nbsp;&nbsp;&nbsp;&nbsp;Have you ever wondered why social media sites like Twitter, Facebook, and Tumblr feel so attuned to your personal interests? The explanation isn’t “There’s an app for that.” but rather, there’s an <i>algorithm</i> for that. Here is an example:</p>
<pre><code>\[r_{u_{}a,s_{}k} = \sum_{i \ne a} {I(u_{}i,s_{}k) w(u_{}a, u_{}i)}\] <a href="http://arachnoid.com/latex/">(view with LaTeX)</a></code></pre>
<p>Memory-based algorithms such as this use the content that we generate to calculate “successful relationships” based on a
matrix of our similarities [Datar]. Tech
companies have adopted to the human impulse for communication by making it
easier to connect with others who share our interests, whether we know them IRL
or URL. Now more than ever, we’re surrounded by thousands of people at every
waking second. According to some cultural critics, this is just one of the many
phenomena spawned by late capitalism. One cultural critic that used this to his
advantage is Jonah Peretti, the creator of BuzzFeed. While studying in college,
Peretti published an article that critiqued cultural capitalism. In the piece,
he states [Wolters]:</p><blockquote>“Identity formation is inextricably
linked to the urge to consume, and therefore the acceleration of capitalism
necessitates an increase in the rate at which individuals assume and shed
identities.”</blockquote><p>Citing the work of Gilles
Deleuze and several other postmodern philosophers, he draws the conclusion that
at some point the flow of identities will become stagnant, thus capitalism must
constantly produce new identities in order to survive. The premise of Buzzfeed is
a manifestation of this, as millions of readers log on to the site to take
pop-culture informed quizzes which generate suitable “pseudo-identities”. Buzzfeed
is not only a reflection of Marxist praxis, but also situationist theory. In
the mid-20<sup>th</sup> century, Situationism developed as a movement in
response to effect of mass media on the individual and society in general. They
believed that individual expression had shifted from being channeled through lived
experience to individual expression by proxy. In more contemporary terms, an analogy
of this would be the ‘self-obsessed’ millennial who would rather take selfies
at the beach to view later on than enjoy the experience firsthand. Through this
line of thought, it could be said that social media serves as this very proxy.</p><br><br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;But how could this be if what we post online is a digital replication of our lived
experience? One could argue that social media is so far reaching that we often
replicate even the most mundane experiences of our lives for the consumption of
others. Scrolling through Facebook timelines and Tumblr dashboards has now
become synonymous with watching television, though this medium is different in
the sense that we can interact with others and contribute content within mere
seconds. The French Marxist theorist Guy Debord explained this phenomenon even
before the existence of the Internet:</p><blockquote>“In
a consumer society, social life is not about living, but about having; the
spectacle uses the image to convey what people need and must have.
Consequently, social life moves further, leaving a state of "having"
and proceeding into a state of "appearing"; namely the appearance of
the image.” [Debord]</blockquote><p>The
downside to this is that outside of the stream of content generated by the
mainstream media and those with ‘actual lives’, it seems like there exists
nothing but banality, a void. On the
contrary, what exists beyond the “spectacle” are infinite tiers of information.
Navigating into this realm may seem like walking in the dark, but it becomes
easier once one is more familiar with their own interests rather than the image
or <i>meme</i> that is projected on to them
(not the ‘ROFL cat’ definition of <i>meme</i>
but the "unit of culture" which reproduces itself and transfers from one
mind to another). This isn’t to say that the Internet cannot affect who we are
as individuals and vice versa, but as stated before, new identities are constantly
emerging. It gets to a point where the corporate ‘creators’ who disseminate social
media cannibalize those who diverge from these hegemonic paths. In his work <i>The</i> <i>Society
of the Spectacle,</i> Debord states:</p><blockquote>“The smug acceptance of
what exists can also merge with purely spectacular rebellion; this reflects the
simple fact that dissatisfaction itself became a commodity as soon as economic
abundance could extend production to the processing of such raw materials.” [Debord]</blockquote><p>In this quote, Debord
explains that the mere act of rebellion could be integrated into the system and
thus exploited. Subjectivity ceases to exist as our individualism becomes
commodified into distinct “experiences” that can be bought and sold. The ultimate
social alienation occurs when people view themselves as commodities and perform
life as a business transaction. Being the creator of your own blog can
certainly enable this commodity fetishism.</p><br><br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;Getting back to how this applies on social media, many users attempt to escape feelings
of alienation by identifying themselves through signifiers and hashtags i.e. Wholock,
SJW (Social Justice Warrior), #Meninist etc. Mainstream outlets pilfer as much content
as they can from these users and repurpose them into bits of information that
are appealing and universal enough for mass marketing. An example of this would
be the site Mic.com. Before this site existed, many users on Tumblr spoke of
their personal experiences in the form of text posts, only to be broadcast to
the few followers who were willing to listen. Now with the advent of Mic.com,
dozens of articles are compiled each week focusing on every issue from race to
sexism to capitalism. These articles generate thousands of notes, they are
almost always the first result when searching any topic. It may seem positive
that such a site exists; one that is accessible to many different types of
readers as well as unique to the individual. The main problem however is that
they often perpetuate a single-story that lacks nuance and simplifies complex
experiences. They rely on the constant creation of identities to subsist,
making human experience into a spectacle. Although algorithms can
help us build knowledge, they also limit our scope. It’s important that we
stray from the paths that we’re expected to follow on the Internet.</p>
<hr>
<footer>
<ol>
<li><a href="http://www.ra.ethz.ch/CDstore/www2007/www2007.org/papers/paper570.pdf">Datar, Mayur, et al. <i>Google News Personalization: Scalable Online.</i> Web.</a></li>
<li><a href="https://www.marxists.org/reference/archive/debord/society.htm">Debord, Guy. <i>The Society of the Spectacle.</i> Web.</a></li>
<li><a href="http://www.critical-theory.com/buzzfeed-founder-responds-to-his-marxist-roots-lol/">Wolters, Eugene. <i>Buzzfeed Founder Responds to His Marxist Roots, "Lol".</i> Web.</a></li>
</ol>
</footer>
</body>
</html>
