<LANGUAGE="VBSCRIPT">
<html>

<body>
<h1>draft #1 on ectogenesis</h1><br>
<p>    The topic that I will be focusing on is ectogenesis, and more specifically, it’s potential effect on gender socialization. Ectogenesis is the development of embryos in artificial conditions outside of the uterus. For centuries, women’s reproductive labor has been a central node of their oppression under capitalism, as they are rendered as incubators for future generations. Some feminists see ectogenesis as a solution to the division of labor that places gestation solely on women, as artificial reproduction would end the burden of pregnancy and the disadvantages that come with it. Ideally, with the onus of reproduction devolved from their bodies, women would no longer face the challenge of acquiring reproductive rights such as abortion, and they would no longer be criminalized for actions that are detrimental to the health of themselves, and subsequently, their fetuses. Presumably, this would radically change society’s notions of gender and allow for new possibilities for sexual minorities and sterile individuals.</p><br><br>

<p>    Seeing as ectogenesis could radically transform the status of women and humanity as we know it, what might be the deterministic consequences of this technology on society? A majority of the scholarship surrounding ectogenesis tends to highlight the aforementioned positive effects that this technology would have. However, some scholars have noted the detrimental impact that this technology could manifest, particularly on the psyche of women and their offspring. This is an interesting topic for sociologists to study because it’s effects will not only be material, but discursive as well. Will the offspring produced through this technology be considered human? Can this technology be incorporated into neoliberalism and used for economic gain?</p><br><br>

<p>    One would probably cite Aldous Huxley’s <i>Brave New World</i> as the original source of the concept of ectogenesis. However, this can be traced back even further to the sixteenth century, when Auroleus Phillipus Theophrastus Bombastus von Hohenheim provided the recipe for creating a <i>homunculus</i>, or a human with no soul, in an artificial womb (Gefland et al):</p>

<blockquote><div>“Let the semen of a man putrefy by itself in a sealed cucurbite with the highest putrefaction of the venter equines [the belly or womb of a horse] for forty days, or until it begins at last to live, move, and be agitated, which can easily be seen. After this time it will be in some degree like a human being, but, nevertheless transparent and without body. If now, after this, it be every day nourished and fed cautiously and prudently with the arcanum of human blood, and kept for forty weeks in the perpetual and equal heat of venter equinus, it becomes thenceforth a true and living infant, having all the members of a child that is born from a woman, but much smaller.”</div></blockquote>

<p>This homunculus was said to have no soul because it was once believed that males passed on the matter of soul and human identity through their semen (Muri). Women’s wombs were seen as ‘clever incubators’, though some have described the placenta as a ‘leaky sieve’, as it is perceptible to harmful contagions (Aristarkhova). Perhaps the first feminist to predict the advent of ectogenesis was Shulamith Firestone. In her seminal work <i>The Dialectic of Sex, </i>Firestone outlines the ways in which pregnancy harms women both physically and socially (Firestone):</p>

<blockquote><div>“The heart of women's oppression is her childbearing and child-rearing roles… To assure the elimination of sexual classes requires the revolt of the underclass (women) and seizure of control of reproduction:... so the end goal of the feminist revolution must be unlike that of the first feminist movement, not just the elimination of male privilege but of the sex distinction itself; genital differences between human beings would no longer matter.”</div></blockquote>

<p>Firestone’s solution for the liberation of women was that women should be granted contraception, abortion rights, and a means to reproduce without reproductive organs. In fact, abortion can be cited as one of the earliest forms of biotechnology (Jasanoff). Firestone’s work paved the way for feminist discourse surrounding reproductive rights as well as ectogenesis.</p><br><br>

<p>    Despite Firestone’s optimistic expectations for ectogenesis, she couldn’t anticipate the dangers that technology might cause for humanity. The cyborg feminist Donna Haraway critiques her argument by stating that she too soon prepared for a future where alienated bodies were controlled by machines and her historical materialism was based on the false premise “that there are natural objects separate from social relations” (Haraway). Haraway is careful to acknowledge “the cyborg as escape from the ills of materialist civilization, and the materialist cyborg as the ruin of civilization” (Muri). She maintains that technology and humanity are one in the same through the concept of the cyborg. This unit in social theory blurs traditional boundaries between organism and machine, human and animal, and between physical and non-physical through the use of science and technology (Sismondo).</p><br><br>

<p>    By stating that she would rather be a cyborg than a goddess, Haraway is condemning ecofeminist notions of the nurturing and constantly available mother, as the dream of an original paradise is regressive to the status of women (Matisons). One scholar notes that ecofeminists tend to dream of “an idyllic time before capitalism’s intervention into and manipulation of nature” (ibid). The sociological concept of social action can be used to examine why some women would be in favor of ectogenesis while others are not. For example, ecofeminists strongly abide by traditional action when it comes to their offspring, and they would rather give natural birth. Emotional action could also explain their decisions: the artificial womb is an ‘evil’ virtual ‘non-space’ since it is not a Mother and does not have a ‘natural’ protective body, therefore “it makes the child’s body more ‘available’ for interference from the outside world, including from the medical profession” (Aristarkhova).</p><br><br>

<p>    On the other hand, cyborg feminists such as Haraway would contend that ecofeminists tend to essentialize female traits while ignoring how this romanticization has been used to oppress women. However, she acknowledges that dreams of a technologically advanced utopia do not always serve liberatory purposes, as seen with the development of Nazi eugenics, which was based on the belief that Aryans contained the seed of ‘authentic’ human nature (Matisons). One criticism of Haraway’s advocacy for technological integration is that “the position from which [she] publishes must surely appear so remote and privileged that the deconstructions it proposes can make no sense” (Field). This is derived from the fact that many developing countries do not have access to technology. In fact, Western middle-class women already use artificial reproduction to exploit the bodies of Third World women through surrogate motherhood (Aristarkhova). Most surrogate mothers come from minority or lower-class backgrounds, yet they cannot afford to utilize this technology. Millions of women would also have to donate their organs for the development of ectogenesis. This is not unsimilar to stem cell research, which would not exist without aborted fetuses (Jasanof).</p><br><br>

<p>    Some critics have questioned the moral permissibility of ectogenesis, not only for mothers but for the cyborg children that it produces. Aristarkhova notes the multiplicity of identities that this offspring would take on: “At once potential research material (scientific object), quasi-citizen (it has legal rights), and potential person (human subject), the embryo has a cyborg liminality in its contested location between science and nature.” She also lists several possible effects of ectogenesis (Aristrarkhova):</p>

<blockquote><div>a) Provide couples with their own child without the complications of IVF and surrogate motherhood;<br><br>

b) Create a pool of spare parts for transplantation – livers, lungs, etc., and provide material for medical research;<br><br>

c) Eliminate wastage of embryonic life caused by abortion;<br><br>

d) Stop burdening women with being ‘reproductive machines’ and hence achieve more equality in childbearing;<br><br>

e) And, last, reduce the possessiveness of natural mothers.</div></blockquote>

<p>This raises several moral, legal, and political concerns. Traditionally, pregnancies could be terminated if a child was handicapped or the mother faced physical/mental health challenges (Jasanof). Research has shown that artificial gestation “increases the chances of survival for the smallest of premature infants and for fetuses with conditions that would benefit from closer monitoring than a womb can provide” (Gefland et al). This is possible because it isolated the child from infection risk, offers specialized feeding, respiratory support and access to specialized physicians, equipment and resources” (Randall and Randall). But under what conditions would mothers be able to abort their children now that gestation can be carried out through machines? Will embryos be considered property and produced in mass quantities, and can parents chose to end its life? One scholar notes (Gefland et al): “Just as interesting, a mother who chose not to continue a pregnancy at any stage could have the fetus transferred to an artificial womb where development would proceed to birth. Can the concept of viability survive in a world where every fertilized egg can be gestated without the direct involvement of a human being?” Perhaps a larger question to consider is, what implications will ectogenesis have on the concept of life?</p><br><br>

<p>    Jasanoff notes: “Michel Foucault famously called attention to the conversion of life, or bios, into the subject matter of political action,” which is to say that bodies can be used for political means. For example, though conservatives would normally reject ectogenesis, they will consider it a “necessary evil” to compromise between the interests of women are pronatalist and pro-choice (Gefland et al). In the case of reproduction, women’s pregnancy has specifically been scrutinized by the state, as it is necessary for “conserving and optimizing population at and prior to birth” (Weir). Thus, states practice risk management by imposing policies to discipline women’s health and make them more “responsible” (ibid): </p><blockquote><div><small>“Health promotion programmes have encouraged women to alter their "modifiable risk factors" through public health campaigns: to stop drinking, smoking, and using recreational drugs, to eat sincerely nutritious meals, and take folic acid. However, the risks present in prenatal risk assessment are diverse, and include those risk determinants such as diabetes and parity (number of previous births) that are not subject to modification through intervention in maternal conduct. Fourth, health promotion represents a model of public health that in Canada was displaced during 1994 by population health (Evans, Barer and Marmor 1994; Hayes and Dunn 1998), but risk-based prenatal care has continued unabated. Population health is concerned with the determinants of health in populations rather than in individuals or risk groups; it has been critical of the limitations of "lifestylism" found in health promotion. Conflating prenatal risk with health promotion fails on many grounds.”</small></div></blockquote><p>With the advent of ectogenesis, women might no longer feel the need to maintain perfect health, nor will they face the shame that comes with not being able to have children. However, some women might as if they possess bodies which have failed their natural purpose (Gefald et al).</p><br><br>

<p>    In conclusion, some questions that I pose to fellow sociologists are: if gender is still prevalent at the onset of ectogenesis, will the status of women still be subordinated? Will the humanity change for the better or worse? I have identified these questions because scholarship surrounding ectogenesis does not anticipate how this technology maybe abused. We must remember that technology is shaped by mankind, and therefore it has a propensity for good as well as evil. Aristarkhov suggests that we redefine what it means to be a machine:</p>

<blockquote><div>If negative definitions of the machine represent misogynist tendencies within European philosophy (devaluing mother as machine, that is, as less than human), then feminist thought has to imagine and set forth alternative conceptions of the machine and thus of the maternal body. There is a need to reconsider our traditional ‘denigration of the machine’ in Western thought, especially with reference to new reproductive technologies, and ectogenesis in particular. And this critical evaluation of the maternal and its relation to machines needs to be informed by the feminist critique of reproductive technologies.</div></blockquote>

<hr><h2><b>Citations</b></h2>

<ol><li>Aristarkhova, Irina. 2005. “Ectogenesis and Mother as Machine.” <i>Body &amp; Society</i> 11: 43-59.</li>
<li>Field, Terri. 2000. “Is the Body Essential for Ecofeminism?” <i>Organization &amp; Environment</i> 13(1): 39-60.</li>
<li>Firestone, Shulamith. 1972. <i>The Dialectic of Sex: the Case for Feminist Revolution. </i>New York: Bantam.</li>
<li>Gefland, Scott. and Shook, John R. 2013. <i>Ectogenesis.: Artificial Womb Technology and the Future of Human Reproduction.</i> New York: Rodopi.</li>
<li>Haraway, Donna J. 1991. <i>Simians, Cyborgs, and Women: The Reinvention of Nature</i>. New York: Routledge.</li>
<li>Jasanoff, Sheila. 2012. <i>Science and Public Reason</i>. New York: Routledge.</li>
<li>Matisons, Michelle Renée. 1998. “The New Feminist Philosophy of the Body: Haraway, Butler and Brennan.” <i>The European Journal of Women’s Studies</i> 5: 9-34.</li>
<li>Muri, Allison. 2003. “Of Shit and the Soul: Tropes of Cybernetic Disembodiment in Contemporary Culture.” <i>Body &amp; Society</i> 9(3): 73-92.</li>
<li>Randall, Vernellia. and Randall, Tshaka. 2008. “Built in Obsolescence: The Coming End to the Abortion Debate.” <i>Journal of Health &amp; Biomedical Law</i> 4: 4-6.</li>
<li>Sismondo, Sergio. 2011. <i>An Introduction to Science and Technology Studies</i>. New York: Wiley.</li>
<li>Weir, Lorna. 2006. <i>Pregnancy, Risk and Biopolitics: On the Threshold of the Living Subject.</i> New York: Routledge.</li></ol>
</body>
</html>
